# Generated by Django 6.0.1 on 2026-01-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='symbol',
        ),
        migrations.AddField(
            model_name='voter',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
