# Generated by Django 6.0.1 on 2026-01-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_party_symbol_voter_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='has_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
