# Generated by Django 6.0.1 on 2026-01-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_voter_has_scanned_alter_voter_voter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='name',
            new_name='party_name',
        ),
    ]
